import { readFileSync, writeFileSync, existsSync } from "node:fs";

const HEADER = "# Changelog";
const PREAMBLE = `All notable changes to this project are documented here.
Generated by [Changeloom](https://github.com/firemesscode/drevorod).`;

/**
 * Insert a new release block at the top of CHANGELOG.md (below the header),
 * creating the file if it does not exist. Returns the updated file contents.
 */
export function prependToChangelog(path: string, releaseNotes: string): string {
  const block = releaseNotes.trim();
  let updated: string;

  if (!existsSync(path)) {
    updated = `${HEADER}\n\n${PREAMBLE}\n\n${block}\n`;
  } else {
    const existing = readFileSync(path, "utf8");
    const lines = existing.split("\n");
    // Find the first release heading ("## ...") and insert just before it.
    const insertAt = lines.findIndex((l) => /^##\s/.test(l));
    if (insertAt === -1) {
      updated = `${existing.trimEnd()}\n\n${block}\n`;
    } else {
      const head = lines.slice(0, insertAt).join("\n").trimEnd();
      const tail = lines.slice(insertAt).join("\n").trimStart();
      updated = `${head}\n\n${block}\n\n${tail}`.trimEnd() + "\n";
    }
  }

  writeFileSync(path, updated);
  return updated;
}
