import { getCommits, isGitRepo, resolveRange, lastTag } from "./git.js";
import { renderOfflineNotes } from "./render.js";
import { generateReleaseNotes } from "./claude.js";
import type { Commit, NotesOptions } from "./types.js";

export * from "./types.js";
export { getCommits, isGitRepo, resolveRange, lastTag, parseConventional } from "./git.js";
export { renderOfflineNotes, groupCommits, formatBullet, SECTIONS } from "./render.js";
export { generateReleaseNotes } from "./claude.js";

export interface BuildOptions extends Partial<NotesOptions> {
  /** Range start (defaults to the last tag). */
  from?: string;
  /** Range end (defaults to HEAD). */
  to?: string;
  /** Working directory of the git repo. */
  cwd?: string;
}

export interface BuildResult {
  notes: string;
  commits: Commit[];
  range: { from?: string; to: string; spec: string };
  /** "claude" when generated by the model, "offline" when produced deterministically. */
  source: "claude" | "offline";
}

/**
 * End-to-end: resolve the range, read commits, and produce release notes.
 * Falls back to the deterministic offline renderer when Claude is unavailable,
 * so it always returns usable notes.
 */
export async function buildReleaseNotes(options: BuildOptions = {}): Promise<BuildResult> {
  const cwd = options.cwd;
  if (!isGitRepo(cwd)) {
    throw new Error("Not a git repository. Run Changeloom inside a git work tree.");
  }

  const range = resolveRange(options.from, options.to, cwd);
  const commits = getCommits(range.spec, cwd);

  const notesOptions: NotesOptions = {
    release: options.release ?? range.to,
    repoUrl: options.repoUrl,
    model: options.model ?? process.env.CHANGELOOM_MODEL ?? "claude-opus-4-8",
    offline: options.offline ?? !process.env.ANTHROPIC_API_KEY,
    date: options.date,
  };

  if (notesOptions.offline || commits.length === 0) {
    return { notes: renderOfflineNotes(commits, notesOptions), commits, range, source: "offline" };
  }

  try {
    const notes = await generateReleaseNotes(commits, notesOptions);
    return { notes, commits, range, source: "claude" };
  } catch (err) {
    // Never fail the pipeline because the model was unreachable — degrade gracefully.
    const reason = err instanceof Error ? err.message : String(err);
    process.env.CHANGELOOM_DEBUG && console.error(`[changeloom] Claude failed, using offline renderer: ${reason}`);
    return { notes: renderOfflineNotes(commits, notesOptions), commits, range, source: "offline" };
  }
}
